// generated by scripts/generate-gallery-thumbs.mjs
// do not edit by hand, add or remove photos in assets/girls instead

export interface GalleryPhoto {
  src: string
  srcSet: string
  width: number
  height: number
}

export const galleryPhotos: GalleryPhoto[] = [
  {
    src: '/gallery/DSF1245-320.2e4153da.webp',
    srcSet: '/gallery/DSF1245-320.2e4153da.webp 320w, /gallery/DSF1245-640.540a94d3.webp 640w',
    width: 320,
    height: 320
  },
  {
    src: '/gallery/DSF1247-320.fdb3b401.webp',
    srcSet: '/gallery/DSF1247-320.fdb3b401.webp 320w, /gallery/DSF1247-640.66672b31.webp 640w',
    width: 320,
    height: 320
  },
  {
    src: '/gallery/DSF1252-320.210065e8.webp',
    srcSet: '/gallery/DSF1252-320.210065e8.webp 320w, /gallery/DSF1252-640.9de56aa5.webp 640w',
    width: 320,
    height: 320
  },
  {
    src: '/gallery/DSF1265-320.78188736.webp',
    srcSet: '/gallery/DSF1265-320.78188736.webp 320w, /gallery/DSF1265-640.6e649bd5.webp 640w',
    width: 320,
    height: 320
  },
  {
    src: '/gallery/DSF1276-320.b29e2626.webp',
    srcSet: '/gallery/DSF1276-320.b29e2626.webp 320w, /gallery/DSF1276-640.c6e23a03.webp 640w',
    width: 320,
    height: 320
  },
  {
    src: '/gallery/DSF1280-320.e1e57d65.webp',
    srcSet: '/gallery/DSF1280-320.e1e57d65.webp 320w, /gallery/DSF1280-640.13ee860d.webp 640w',
    width: 320,
    height: 320
  },
  {
    src: '/gallery/DSF1283-320.49f67fc4.webp',
    srcSet: '/gallery/DSF1283-320.49f67fc4.webp 320w, /gallery/DSF1283-640.b8306454.webp 640w',
    width: 320,
    height: 320
  },
  {
    src: '/gallery/DSF1297-320.6080bdbe.webp',
    srcSet: '/gallery/DSF1297-320.6080bdbe.webp 320w, /gallery/DSF1297-640.80132a04.webp 640w',
    width: 320,
    height: 320
  },
  {
    src: '/gallery/DSF1298-320.05fbdfee.webp',
    srcSet: '/gallery/DSF1298-320.05fbdfee.webp 320w, /gallery/DSF1298-640.dd1ea06e.webp 640w',
    width: 320,
    height: 320
  },
  {
    src: '/gallery/DSF1300-320.c73d1b77.webp',
    srcSet: '/gallery/DSF1300-320.c73d1b77.webp 320w, /gallery/DSF1300-640.580379ee.webp 640w',
    width: 320,
    height: 320
  },
  {
    src: '/gallery/DSF1302-320.24f88865.webp',
    srcSet: '/gallery/DSF1302-320.24f88865.webp 320w, /gallery/DSF1302-640.4a2784ca.webp 640w',
    width: 320,
    height: 320
  },
  {
    src: '/gallery/DSF1303-320.812a1afc.webp',
    srcSet: '/gallery/DSF1303-320.812a1afc.webp 320w, /gallery/DSF1303-640.e5edc35d.webp 640w',
    width: 320,
    height: 320
  },
  {
    src: '/gallery/DSF1309-320.79208610.webp',
    srcSet: '/gallery/DSF1309-320.79208610.webp 320w, /gallery/DSF1309-640.76bb4e04.webp 640w',
    width: 320,
    height: 320
  },
  {
    src: '/gallery/DSF1310-320.c0affa55.webp',
    srcSet: '/gallery/DSF1310-320.c0affa55.webp 320w, /gallery/DSF1310-640.bea794da.webp 640w',
    width: 320,
    height: 320
  },
  {
    src: '/gallery/DSF1327-320.93a964a7.webp',
    srcSet: '/gallery/DSF1327-320.93a964a7.webp 320w, /gallery/DSF1327-640.64afe46d.webp 640w',
    width: 320,
    height: 320
  },
  {
    src: '/gallery/DSF1329-320.dedf46ca.webp',
    srcSet: '/gallery/DSF1329-320.dedf46ca.webp 320w, /gallery/DSF1329-640.939d76f2.webp 640w',
    width: 320,
    height: 320
  },
  {
    src: '/gallery/DSF1332-320.97044982.webp',
    srcSet: '/gallery/DSF1332-320.97044982.webp 320w, /gallery/DSF1332-640.371526ce.webp 640w',
    width: 320,
    height: 320
  },
  {
    src: '/gallery/DSF1347-320.96894c46.webp',
    srcSet: '/gallery/DSF1347-320.96894c46.webp 320w, /gallery/DSF1347-640.2088443a.webp 640w',
    width: 320,
    height: 320
  },
  {
    src: '/gallery/DSF1349-320.fbba3164.webp',
    srcSet: '/gallery/DSF1349-320.fbba3164.webp 320w, /gallery/DSF1349-640.bb2f56a0.webp 640w',
    width: 320,
    height: 320
  },
  {
    src: '/gallery/DSF1352-320.3f6b3716.webp',
    srcSet: '/gallery/DSF1352-320.3f6b3716.webp 320w, /gallery/DSF1352-640.22c03f0d.webp 640w',
    width: 320,
    height: 320
  },
  {
    src: '/gallery/DSF1354-320.3f438afe.webp',
    srcSet: '/gallery/DSF1354-320.3f438afe.webp 320w, /gallery/DSF1354-640.f65c6b40.webp 640w',
    width: 320,
    height: 320
  },
  {
    src: '/gallery/DSF1360-320.55f4bc61.webp',
    srcSet: '/gallery/DSF1360-320.55f4bc61.webp 320w, /gallery/DSF1360-640.273103fb.webp 640w',
    width: 320,
    height: 320
  },
  {
    src: '/gallery/DSF1372-320.e9a21e51.webp',
    srcSet: '/gallery/DSF1372-320.e9a21e51.webp 320w, /gallery/DSF1372-640.333862c7.webp 640w',
    width: 320,
    height: 320
  },
  {
    src: '/gallery/DSF1376-320.5a00c5ff.webp',
    srcSet: '/gallery/DSF1376-320.5a00c5ff.webp 320w, /gallery/DSF1376-640.ca1fc7a7.webp 640w',
    width: 320,
    height: 320
  },
  {
    src: '/gallery/DSF1413-320.bdde4b8e.webp',
    srcSet: '/gallery/DSF1413-320.bdde4b8e.webp 320w, /gallery/DSF1413-640.48da4fb1.webp 640w',
    width: 320,
    height: 320
  },
  {
    src: '/gallery/DSF1419-320.eb2a15a7.webp',
    srcSet: '/gallery/DSF1419-320.eb2a15a7.webp 320w, /gallery/DSF1419-640.d4e16ad8.webp 640w',
    width: 320,
    height: 320
  },
  {
    src: '/gallery/IMG-2064-HEIC-320.8c6f0de7.webp',
    srcSet: '/gallery/IMG-2064-HEIC-320.8c6f0de7.webp 320w, /gallery/IMG-2064-HEIC-640.3a01653d.webp 640w',
    width: 320,
    height: 320
  },
  {
    src: '/gallery/IMG-2067-HEIC-320.b77ec941.webp',
    srcSet: '/gallery/IMG-2067-HEIC-320.b77ec941.webp 320w, /gallery/IMG-2067-HEIC-640.39f83b7f.webp 640w',
    width: 320,
    height: 320
  },
  {
    src: '/gallery/IMG-2078-HEIC-320.2b23f7be.webp',
    srcSet: '/gallery/IMG-2078-HEIC-320.2b23f7be.webp 320w, /gallery/IMG-2078-HEIC-640.da0c5148.webp 640w',
    width: 320,
    height: 320
  },
  {
    src: '/gallery/IMG-2913-HEIC-320.6e99270f.webp',
    srcSet: '/gallery/IMG-2913-HEIC-320.6e99270f.webp 320w, /gallery/IMG-2913-HEIC-640.1cdc27d8.webp 640w',
    width: 320,
    height: 320
  },
  {
    src: '/gallery/IMG-2914-HEIC-320.ce7eb79c.webp',
    srcSet: '/gallery/IMG-2914-HEIC-320.ce7eb79c.webp 320w, /gallery/IMG-2914-HEIC-640.0fcfa31d.webp 640w',
    width: 320,
    height: 320
  },
  {
    src: '/gallery/IMG-2930-HEIC-320.d4e00cd9.webp',
    srcSet: '/gallery/IMG-2930-HEIC-320.d4e00cd9.webp 320w, /gallery/IMG-2930-HEIC-640.85b00fff.webp 640w',
    width: 320,
    height: 320
  },
  {
    src: '/gallery/IMG-2940-HEIC-320.20d3cd52.webp',
    srcSet: '/gallery/IMG-2940-HEIC-320.20d3cd52.webp 320w, /gallery/IMG-2940-HEIC-640.870cf6bc.webp 640w',
    width: 320,
    height: 320
  },
  {
    src: '/gallery/IMG-2943-HEIC-320.9b0300f2.webp',
    srcSet: '/gallery/IMG-2943-HEIC-320.9b0300f2.webp 320w, /gallery/IMG-2943-HEIC-640.a89bf981.webp 640w',
    width: 320,
    height: 320
  },
  {
    src: '/gallery/IMG-2948-HEIC-320.9e364d38.webp',
    srcSet: '/gallery/IMG-2948-HEIC-320.9e364d38.webp 320w, /gallery/IMG-2948-HEIC-640.2aa8abbc.webp 640w',
    width: 320,
    height: 320
  },
  {
    src: '/gallery/IMG-2960-HEIC-320.47c3837f.webp',
    srcSet: '/gallery/IMG-2960-HEIC-320.47c3837f.webp 320w, /gallery/IMG-2960-HEIC-640.40d9114f.webp 640w',
    width: 320,
    height: 320
  },
  {
    src: '/gallery/IMG-2965-HEIC-320.e5c146a2.webp',
    srcSet: '/gallery/IMG-2965-HEIC-320.e5c146a2.webp 320w, /gallery/IMG-2965-HEIC-640.b00cab94.webp 640w',
    width: 320,
    height: 320
  },
  {
    src: '/gallery/IMG-2974-HEIC-320.fb4a3c04.webp',
    srcSet: '/gallery/IMG-2974-HEIC-320.fb4a3c04.webp 320w, /gallery/IMG-2974-HEIC-640.d1557cfb.webp 640w',
    width: 320,
    height: 320
  },
  {
    src: '/gallery/IMG-2986-HEIC-320.eed011cf.webp',
    srcSet: '/gallery/IMG-2986-HEIC-320.eed011cf.webp 320w, /gallery/IMG-2986-HEIC-640.3f563d30.webp 640w',
    width: 320,
    height: 320
  },
  {
    src: '/gallery/IMG-2997-HEIC-320.afae858b.webp',
    srcSet: '/gallery/IMG-2997-HEIC-320.afae858b.webp 320w, /gallery/IMG-2997-HEIC-640.6f350998.webp 640w',
    width: 320,
    height: 320
  },
  {
    src: '/gallery/IMG-3001-HEIC-320.cee0c25c.webp',
    srcSet: '/gallery/IMG-3001-HEIC-320.cee0c25c.webp 320w, /gallery/IMG-3001-HEIC-640.3c5f706e.webp 640w',
    width: 320,
    height: 320
  },
  {
    src: '/gallery/IMG-3017-HEIC-320.20741cdb.webp',
    srcSet: '/gallery/IMG-3017-HEIC-320.20741cdb.webp 320w, /gallery/IMG-3017-HEIC-640.3af7b3e4.webp 640w',
    width: 320,
    height: 320
  },
  {
    src: '/gallery/IMG-3047-HEIC-320.c43d53a0.webp',
    srcSet: '/gallery/IMG-3047-HEIC-320.c43d53a0.webp 320w, /gallery/IMG-3047-HEIC-640.3d010564.webp 640w',
    width: 320,
    height: 320
  },
  {
    src: '/gallery/IMG-3054-HEIC-320.730cb1da.webp',
    srcSet: '/gallery/IMG-3054-HEIC-320.730cb1da.webp 320w, /gallery/IMG-3054-HEIC-640.f8472a8a.webp 640w',
    width: 320,
    height: 320
  }
]
